{% set name = "deltadb" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deltadb-{{ version }}.tar.gz
  sha256: 7479822d028d3edf24d1517730877a0ab417fa8291e1d1b69f3eb421b9a58f77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.12.0,<4.0.0
    - polars >=1.4.1,<2.0.0
    - deltalake >=0.18.2,<0.19.0
    - ipython >=8.26.0,<9.0.0

test:
  imports:
    - deltadb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uname-n/deltadb
  summary: lightweight, fast, and scalable database built on polars and deltalake
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
